### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by babinyurii** [oleksulkowski/Syn-CpG-Spacer#1]
Requirements file should be includes into the repository.

**Comment by oleksulkowski** [comment]
Thank you. The `Syn-CpG-Spacer.yml` file contains the required packages. For clarity, I can rename it to `environment.yml` and add dependency versions to prevent breaking changes.

**Comment by babinyurii** [comment]
I think renaming yml and adding versions to it will solve this issue.
