### ISSUE TITLE
Classes into a file 

### ISSUE THREAD

**Issue by babinyurii** [oleksulkowski/Syn-CpG-Spacer#3]
You may consider putting your main classes (Codon and Gene) into a separate file. This will make your main index.py module more readable and make future code support easier.

**Comment by oleksulkowski** [comment]
Thank you. I considered this when designing the program. Unfortunately, the `panel convert` command cannot import local relative modules into the Pyodide PWA, so I had to place everything in one file, `index.py`, as per https://panel.holoviz.org/how_to/wasm/convert.html.

I explored different solutions, however, they clashed with my concept of running this as a PWA from a single GitHub repository. For example, I could have created a PyPi package from the algorithm classes and constants, and imported them. I think this would have necessitated dividing the algorithm package and GUI/PWA into separate repositories. Therefore, I opted for the simplest option.

For this reason, would you be happy to leave this issue and #2  without resolution? I'd be happy to separate the files if the libraries make it possible in the future. If not, I can look into reworking the software.

**Comment by babinyurii** [comment]
Ок, i close this  issue and the related one
